# pyproject.toml

[tool.poetry]
name = "rpa_landuse_app"
version = "0.1.0"
description = ""
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "src", from = "."}]

[tool.poetry.dependencies]
python = "^3.9"
pyreadr = ">=0.4.9"
pandas = ">=2.1.0"
pyarrow = ">=14.0.1"
fastparquet = ">=2023.10.1"
pytest = ">=7.4.0"
fastapi = ">=0.104.1"
uvicorn = ">=0.24.0"
"mysql-connector-python" = ">=8.2.0"
"python-dotenv" = ">=1.0.0"
pydantic = ">=2.5.2"
packaging = "<24,>=16.8"
httpx = ">=0.25.0"
"pytest-asyncio" = ">=0.23.0"
"fastapi-cache2" = ">=0.2.1"
redis = ">=5.0.1"
slowapi = ">=0.1.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"