[server]
# Server settings
enableXsrfProtection = true
enableCORS = false

# Force pip instead of uv
deploymentTarget = "pip"

[browser]
gatherUsageStats = false

[theme]
primaryColor="#3d7b6c"
backgroundColor="#f5f5f5"
secondaryBackgroundColor="#e6f7f2"
textColor="#262730"
font="sans serif" 